FROM golang:1.23.1-alpine AS build

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY pkg ./pkg
COPY services/task-engine ./services/task-engine

RUN CGO_ENABLED=0 GOOS=linux go build -o /out/task-engine ./services/task-engine

FROM alpine:3.20

RUN adduser -D -H appuser
USER appuser

COPY --from=build /out/task-engine /task-engine

EXPOSE 8081

ENTRYPOINT ["/task-engine"]
